ExampleProject/urls.py
from django.contrib import admin
from django.urls import path, include
from quizzes.views import quiz_upload

urlpatterns = [
    path('quizzes/', include('quizzes.urls')),
    path('admin/', admin.site.urls),
    path('nested_admin/', include('nested_admin.urls')),
    path('upload-csv/', quiz_upload, name="quiz_upload"),
]

quizzes/urls.py
from django.urls import path
from . import views

app_name = 'quizzes'

urlpatterns = [
    # ex: /quizzes/
    # Shows all quizzes
    path('', views.IndexView.as_view(), name='index'),

    # ex: /quizzes/1/
    # Shows all categories and questions of quiz
    # The 'name' value as called by the {% url %} template tag
    path('<int:pk>/', views.QuizDetailView.as_view(), name='quiz_detail'),

    # ex: /quizzes/1/1/question/1
    # Pages through the quiz questions
    path('<int:quiz_id>/<int:category_id>/<int:question_id>/', views.take_quiz, name='take_quiz'),

    # ex: /quizzes/1/1/question/1/select_answer
    path('<int:quiz_id>/<int:category_id>/<int:question_id>/select_answer/', views.select_answer, name='select_answer'),

    # nothing is rendered on this page, just a quick jump between the index and take_quiz
    path('<int:quiz_id>/<int:category_id>/startquiz/', views.start_new_quiz, name='start_new_quiz'),

    # ex: /quizzes/feedback/user_id
    # Shows the user the feedback for their quiz
    path('feedback/<int:user_id>/', views.feedback, name='feedback'),

    # ex: /quizzes/feedback/user_id/pdf
    # Shows the user the feedback for their quiz
    path('feedback/<int:user_id>/pdf/', views.get_feedback_pdf, name='get_feedback_pdf'),
]

quizzes/models.py
import datetime
import uuid
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from model_utils.managers import InheritanceManager
from jsonfield import JSONField


# Structure Idea comes from:
# https://codereview.stackexchange.com/questions/114962/model-classes-for-a-quiz-app-in-django
# Rest was built following alongside Django Software Foundation's Writing your first Django app Tutorial
# https://docs.djangoproject.com/en/3.0/intro/tutorial01/

class Quiz(models.Model):
    """Stores the name of the quiz and all data related to the quiz"""

    # Question content
    name = models.CharField(_("Quiz Name"), max_length=200, blank=True, null=True)
    pub_date = models.DateTimeField('date created')
    description = models.CharField(_("Quiz Description"), max_length=200, blank=True, null=True)
    active_quiz = models.BooleanField("Active", default=False)

    def __str__(self):
        return self.name

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

    def check_active(self):
        if self.active_quiz is True:
            return True
        else:
            return False

    def get_queryset(self):
        """Return the last five published quizzes"""
        return Quiz.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]

    # The following are functions for session variables

    def get_quiz_questions(self):
        return self.question_set.all().select_subclasses()

    def get_quiz_categories(self):
        return self.category_set.all().select_subclasses()

    def session_question_list(self):
        return str(self.id) + "_quiz_question_list"

    def session_quiz_data(self):
        return str(self.id) + "_quiz_data"

    def session_cat_data(self):
        return str(self.id) + "_cat_data"

    def session_norm_data(self):
        return str(self.id) + "_norm_data"

    def session_feedback(self):
        return str(self.id) + "_feedback"

    def session_response_id(self):
        return str(self.id) + "_response_id"

    class Meta:
        verbose_name_plural = 'Quizzes'
        db_table = "quiz"


class Category(models.Model):
    """Stores the name of the category and the related quiz"""
    # Parent object
    parent_quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE, blank=True, null=True)

    # Category content
    category_name = models.CharField(_("Category Name"), max_length=200, blank=True, null=True)
    order = models.IntegerField(blank=True, null=True)
    description = models.CharField(_("Category Description"), max_length=2000, blank=True, null=True)
    score = models.FloatField(default=0)
    objects = InheritanceManager()

    def __str__(self):
        return self.category_name

    class Meta:
        db_table = "category"
        verbose_name_plural = 'Categories'


class Question(models.Model):
    """Each question is linked to a quiz and a category"""
    # Parent Object
    parent_quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE, blank=True, null=True)
    parent_category = models.ForeignKey(Category, on_delete=models.CASCADE, blank=True, null=True)
    objects = InheritanceManager()

    # Question Content
    question_text = models.CharField(_("Question"), max_length=600, blank=True, null=True)

    def __str__(self):
        return self.question_text

    def get_answers(self):
        return [
            (answer.id, answer.answer_text, answer.answer_weight)
            for answer in Answer.objects.filter(question=self)
        ]

    class Meta:
        db_table = "question"


class Answer(models.Model):
    """Each answer is linked to a quiz, category, and question"""
    # Parent object
    parent_quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE, blank=True, null=True)
    parent_category = models.ForeignKey(Category, on_delete=models.CASCADE, blank=True, null=True)
    parent_question = models.ForeignKey(Question, on_delete=models.CASCADE, blank=True, null=True)

    # Answer content
    answer_text = models.CharField(_("Answer"), max_length=600, blank=True, null=True)
    answer_selected = models.BooleanField(default=False)
    answer_weight = models.FloatField(default=1.0)

    def __str__(self):
        return self.answer_text

    def get_quiz_feedback(self):
        return self.feedback_set.all().select_subclasses()

    class Meta:
        db_table = "answer"


class Feedback(models.Model):
    """
    Feedback is provided to each quiz participant upon completion.
    This feedback is tied to the selected answer for each question.
    """
    # Parent object
    parent_quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE, blank=True, null=True)
    parent_category = models.ForeignKey(Category, on_delete=models.CASCADE, blank=True, null=True)
    parent_question = models.ForeignKey(Question, on_delete=models.CASCADE, blank=True, null=True)
    parent_answer = models.ForeignKey(Answer, on_delete=models.CASCADE, blank=True, null=True)

    # Feedback content
    feedback_type = models.CharField(_("Feedback Type"), max_length=200, blank=True, null=True)
    feedback_text = models.CharField(_("Feedback"), max_length=600, blank=True, null=True)
    objects = InheritanceManager()

    def __str__(self):
        return self.feedback_text

    class Meta:
        db_table = "feedback"
        verbose_name_plural = 'Feedback'


class UserResponse(models.Model):
    """"""
    parent_quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE, blank=True, null=True)
    response_id = models.IntegerField(blank=True, null=True)
    response_data = JSONField(null=True)

    def __str__(self):
        return str(self.response_id)

    class Meta:
        db_table = "response"
        verbose_name_plural = 'Responses'

quizzes/views.py
import csv, io, datetime
from django.contrib.auth.decorators import permission_required
from django.views.decorators.cache import cache_page
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from .models import Quiz, Category, Question, Answer, Feedback, UserResponse
from .render import Render
from django.core.exceptions import ObjectDoesNotExist
from random import choice


# Built following alongside Django Software Foundation's Writing your first Django app Tutorial
# https://docs.djangoproject.com/en/3.0/intro/tutorial01/

class IndexView(generic.ListView):
    template_name = 'quizzes/index.html'
    context_object_name = 'latest_quiz_list'

    def get_queryset(self):
        """Return the last five published, active quizzes"""
        return Quiz.objects.filter(active_quiz=True).order_by('-pub_date')[:5]


class QuizDetailView(generic.DetailView):
    model = Quiz
    template_name = 'quizzes/quiz_detail.html'

    def get_queryset(self):
        """Return the active quizzes"""
        return Quiz.objects.filter(active_quiz=True).order_by('-pub_date')


@permission_required('admin.can_add_log_entry')
def quiz_upload(request):
    """
    This is a function that lets the superuser upload a CSV to create or edit a quiz.
    """
    template = "quizzes/quiz_upload.html"
    prompt = {
        'headerorder': 'Order of the CSV header should be Quiz name, pub_date, description',
        'order': 'Order for rest of CSV should be Quiz name, '
                 'category_name, question_text, answer_text, answer_weight, feedback_text',
        'feedbacknote': 'If you do not plan on including feedback for an answer put No Feedback for feedback_text',
    }
    error_msg = 'This is csv file is not formatted correctly, please check the file and try again'

    if request.method == 'GET':
        return render(request, template, prompt)

    csv_file = request.FILES['file']

    # Check if the submitted file is .csv format
    if not csv_file.name.endswith('.csv'):
        messages.error(request, template, 'This is not a csv file')

    quiz_contents = csv_file.read().decode('UTF-8')
    io_string = io.StringIO(quiz_contents)

    # Create/Update Quiz using first row of csv, check for proper format
    csv_header = next(csv.reader(io_string, delimiter=',', quotechar="|"))
    try:
        # Added an extra layer of error catching, this will try to enter the time in the full datetime format
        # if not in datetime %Y-%m-%d %H:%M:%S.%f', then it will just try the date given
        try:
            quiz_obj, quiz_created = Quiz.objects.update_or_create(
                name=csv_header[0],
                pub_date=datetime.datetime.strptime(csv_header[1], '%Y-%m-%d %H:%M:%S.%f'),
                description=csv_header[2],
                active_quiz=True,
            )
        except ValueError:
            quiz_obj, quiz_created = Quiz.objects.update_or_create(
                name=csv_header[0],
                pub_date=csv_header[1],
                description=csv_header[2],
                active_quiz=True,
            )

    # If there is an Index Error, the created object is deleted and the page is reloaded with the error message
    except IndexError:
        try:
            Quiz.objects.filter(quiz_name=quiz_obj.quiz_name).delete()
        except ObjectDoesNotExist:
            pass
        render(request, template, prompt)
        messages.error(request, error_msg)

    # Creating sets to check old upload vs new upload
    if quiz_created is False:
        categories = quiz_obj.category_set.all()
        questions = quiz_obj.question_set.all()
        answers = quiz_obj.answer_set.all()
        feedback_set = quiz_obj.feedback_set.all()
        quiz_c_old = set(c.category_name for c in categories)
        quiz_c_new = set()
        quiz_q_old = set(q.question_text for q in questions)
        quiz_q_new = set()
        quiz_a_old = set((a.answer_text, a.answer_weight) for a in answers)
        quiz_a_new = set()
        quiz_f_old = set(f.feedback_text for f in feedback_set)
        quiz_f_new = set()

    # Now create the rest of the Quiz elements, u
    for row in csv.reader(io_string, delimiter=',', quotechar="|"):
        try:
            category_obj, created = Category.objects.update_or_create(
                parent_quiz=quiz_obj,
                category_name=row[1],
                order=0,
                description='',
                score=0
            )
            question_obj, created = Question.objects.update_or_create(
                parent_quiz=quiz_obj,
                parent_category=category_obj,
                question_text=row[2]
            )
            answer_obj, created = Answer.objects.update_or_create(
                parent_quiz=quiz_obj,
                parent_category=category_obj,
                parent_question=question_obj,
                answer_text=row[3],
                answer_selected=False,
                answer_weight=row[4]
            )
            feedback_obj, created = Feedback.objects.update_or_create(
                parent_quiz=quiz_obj,
                parent_category=category_obj,
                parent_question=question_obj,
                parent_answer=answer_obj,
                feedback_type='',
                feedback_text=row[5]
            )
            if quiz_created is False:
                quiz_c_new.add(category_obj.category_name)
                quiz_q_new.add(question_obj.question_text)
                quiz_a_new.add((answer_obj.answer_text, answer_obj.answer_weight))
                quiz_f_new.add(feedback_obj.feedback_text)

        # If there is an error in the format of the CSV, Error raised.
        # Anything that was created relating to the quiz is deleted and the page is reloaded with an error message
        except IndexError or ValueError:
            try:
                Feedback.objects.filter(parent_quiz=quiz_obj).delete()
                Answer.objects.filter(parent_quiz=quiz_obj).delete()
                Question.objects.filter(parent_quiz=quiz_obj).delete()
                Category.objects.filter(parent_quiz=quiz_obj).delete()
                Quiz.objects.filter(quiz_name=quiz_obj.quiz_name).delete()
            except ObjectDoesNotExist:
                pass
            render(request, template, prompt)
            messages.error(request, error_msg)

    # Checking what was removed between uploads
    if quiz_created is False:
        removed_c = quiz_c_old.difference(quiz_c_new)
        removed_q = quiz_q_old.difference(quiz_q_new)
        removed_a = quiz_a_old.difference(quiz_a_new)
        removed_f = quiz_f_old.difference(quiz_f_new)

        # Removing anything that was not in the new csv
        if removed_c:
            for i in removed_c:
                category = Category.objects.filter(parent_quiz=quiz_obj, category_name=str(i)).get()
                Feedback.objects.filter(parent_quiz=quiz_obj, parent_category=category).delete()
                Answer.objects.filter(parent_quiz=quiz_obj, parent_category=category).delete()
                Question.objects.filter(parent_quiz=quiz_obj, parent_category=category).delete()
                Category.objects.filter(parent_quiz=quiz_obj, category_name=str(i)).delete()
        if removed_q:
            for i in removed_q:
                try:
                    question = Question.objects.filter(parent_quiz=quiz_obj, question_text=str(i)).get()
                    Feedback.objects.filter(parent_quiz=quiz_obj, parent_question=question).delete()
                    Answer.objects.filter(parent_quiz=quiz_obj, parent_question=question).delete()
                    Question.objects.filter(parent_quiz=quiz_obj, question_text=str(i)).delete()
                except ObjectDoesNotExist:
                    pass
        if removed_a:
            for i in removed_a:
                try:
                    answer = Answer.objects.filter(parent_quiz=quiz_obj, answer_text=str(i[0]), answer_weight=i[1]).get()
                    Feedback.objects.filter(parent_quiz=quiz_obj, parent_answer=answer).delete()
                    Answer.objects.filter(parent_quiz=quiz_obj, answer_text=str(i[0]), answer_weight=i[1]).delete()
                except ObjectDoesNotExist:
                    pass
        if removed_f:
            for i in removed_f:
                try:
                    Feedback.objects.filter(parent_quiz=quiz_obj, feedback_text=str(i)).delete()
                except ObjectDoesNotExist:
                    pass

    context = {
        "success": 'The quiz was uploaded successfully',
        'headerorder': 'Order of the CSV header should be Quiz name, pub_date, description',
        'order': 'Order for rest of CSV should be Quiz name, '
                 'category_name, question_text, answer_text, answer_weight, feedback_text',
        'feedbacknote': 'If you do not plan on including feedback for an answer put No Feedback for feedback_text',
    }

    return render(request, template, context)


def generate_new_id(quiz_id):
    range_low = quiz_id*1000
    range_high = range_low + 999
    ids = set(range(range_low, range_high))
    used_ids = set(UserResponse.objects.values_list('response_id', flat=True))
    return choice(list(ids - used_ids))


def create_user_response(quiz_id, *args):
    """
    Function to create a new response database entry,
    response_id is left default to be produced with the
    UserResponse class's generate_new_id function

    Returns the UserResponse object response_id
    """
    quiz = get_object_or_404(Quiz, pk=quiz_id)
    if args:
        response_obj, created = UserResponse.objects.update_or_create(
            parent_quiz=quiz,
            response_id=args[0]['user_id'],
            defaults=dict(response_data=args[0]['quiz_dictionary']),

quizzes/templates/quizzes/feedback.html
<h1>{{ quiz.name }}</h1>


{% for item in sorted_scores_limit.items %}
    {% for score in norm_scores.items %}
        {% if item.0 == score.0 %}
        {% for category,feedback in feed_dict.items %}
            {% if forloop.counter == forloop.parentloop.counter %}
            <h2>{{ category }}: {{ score.1 }}</h2>
            <ul>
            {% for questiontext, feedbacktext in feedback.items %}
                {% if feedbacktext == None %}
                {% else %}
                <h3>{{questiontext}}</h3>
                <ul>
                <li>{{feedbacktext}}</li>
                </ul>
                {% endif %}
            {% endfor %}
            </ul>
            {% endif %}
        {% endfor %}
        {% endif %}
    {% endfor %}
{% endfor %}

<form action="{% url 'quizzes:get_feedback_pdf' user_id %}" method="post">
    {% csrf_token %}
    <button type="submit">Get Complete Feedback Report</button>
</form>

<a href="{% url 'quizzes:index' %}">Back to Quiz Index</a>

</html>

quizzes/templates/quizzes/get_feedback_pdf.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Feedback Report</title>
    <style type="text/css">
        @page {
            size: A4;
            margin: 1cm;
        }

        .table {
            width: 25%;
            max-width: 25%;
            margin-bottom: 5px;
            background-color: #fff;
        }

        .table th,
        .table td {
            padding: 5px;
            vertical-align: top;
            border-top: 1px solid #000;
            text-align: center;
        }

        .table thead th {
            vertical-align: bottom;
            border-bottom: 2px solid #000;
        }

        .table tbody + tbody {
            border-top: 2px solid #000;
        }

        .table .table {
            background-color: #fff;
        }

        .list-group {
            display: block;
            width: 25%;
            list-style: none;
            margin-top: 15px;
            margin-bottom: 15px;
        }

        .list-group p {
            width: 25%;
            height: 20px;
            line-height: 20px;
            list-style: none;
            font-size: 1.1em;
        }

    </style>
</head>
<body>

<div class="container">
    <div class="card">
        <div class="card-header">
            <h3>Feedback Report - {{ today | date:"Y/m/d" }}</h3>
        </div>

        <div class="list-group">
            <strong><p>User ID: {{ user_id }} </p></strong>
        </div>

        <table class="table">
            <thead>
            <tr>
                <th>Category</th>
                <th>Score</th>
            </tr>
            </thead>
            <tbody>
            {% for category,score in norm_scores.items %}
                <tr>
                    <td>{{ category }}</td>
                    <td>{{ score }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>

<div class="container">
    <div class="card">
        <div class="card-header">
            {% for category, data in quiz_data.items %}
                {% for score in norm_scores.items %}
                    {% if category == score.0 %}
                    {% for category,feedback in feed_dict.items %}
                        {% if forloop.counter == forloop.parentloop.counter %}
                            <h2>{{ category }}: {{ score.1 }}</h2>
                            <ul>
                                {% for questiondata in data.items %}
                                    <p><h3>{{questiondata.0}}</h3></p>
                                <ul>
                                <p><strong>You selected:</strong> {{questiondata.1}}</p>
                                    {% for questiontext, feedbacktext in feedback.items %}
                                        {% if questiondata.0 is questiontext %}
                                            {% if feedbacktext %}
                                            <p>{{feedbacktext}}</p>
                                            {% elif feedbacktext is None %}
                                            <p>No feedback for this question</p>
                                            {% endif %}
                                        {% endif %}
                                    {% endfor %}
                                </ul>
                                {% endfor %}
                            </ul>
                        {% endif %}
                    {% endfor %}
                    {% endif %}
                {% endfor %}
            {% endfor %}
        </div>
    </div>
</div>
</body>
</html>

quizzes/templates/quizzes/index.html
<!DOCTYPE html>
<html lang="en">

<h1>Quiz Index</h1>

{% if latest_quiz_list %}

{% for quiz in latest_quiz_list %}
    {% if quiz.active_quiz is True %}
    <ul>
        <li> {{ quiz.name }}
            <ul><p><a href="{% url 'quizzes:quiz_detail' quiz.id %}">Info</a> |
                <a href="{% url 'quizzes:start_new_quiz' quiz.id quiz.question_set.first.id %}">Take Quiz</a></p></ul>
        </li>
    </ul>
    {% endif %}
 {% endfor %}

{% else %}
    <p>No quizzes are available.</p>
{% endif %}

</html>

quizzes/templates/quizzes/quiz_detail.html
<!DOCTYPE html>
<html lang="en">

<div class="container">
    <div class="card">
        <div class="card-header">
            <h1>{{ quiz.name }}: {{ quiz.description }}</h1>
        </div>
    </div>
</div>

<div>
<u1>
    {% for category in quiz.category_set.all %}
        <div>
            <strong><ul>{{ category.category_name }}</ul></strong>
        </div>
        {% for question in category.question_set.all %}
        <div>
            <ul><ul><li>{{question.question_text}}</li></ul></ul>
        </div>
        {% endfor %}
    {% endfor %}
</u1>
</div>

</html>

quizzes/templates/quizzes/quiz_upload.html
<!DOCTYPE html>
<html lang="en">
<H3>Upload CSV</H3>
{% if messages %}
    <div>
        <strong>{{messages}}</strong>
    </div>
{% else %}
<div>
    <p>{{success}}</p>
    <p><strong>CSV Formatting:</strong></p>
    <ul>
        <p>{{headerorder}}</p>
        <p>{{order}}</p>
        <p><strong>Note: </strong> {{feedbacknote}}</p>
    </ul>
</div>
<div>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <label>Upload a file</label>
        <input type="file" name="file">
        <p>Only accepts CSV files</p>
        <button type="submit">Upload</button>
    </form>
</div>
{% endif %}

</html>

quizzes/templates/quizzes/scratch.html
For take_quiz

    <h3>{{ question.question_text}}</h3>
        {% for answer in question.answer_set %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">{{ answer.answer_text}}</label><br>
        {% endfor %}
    <input type="submit" value="Next Section">
    {% else %}

For feedback

quizzes/templates/quizzes/take_quiz.html
<!DOCTYPE html>
<html lang="en">

<head>
<meta charset="utf-8">
<!-- styles -->
<link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">

<!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
<!--[if lt IE 9]>
<script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

</head>

<body>
<div class="page-header">
    <div class="container">
        <h1>{{ question.parent_quiz.name }}</h1>
    </div>
</div>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<div class="container">
    <p class="lead">{{ question.question_text }}</p>
    <form action="{% url 'quizzes:select_answer' question.parent_quiz.id question.parent_category.id question.id %}" method="post">
        {% csrf_token %}
            {% for answer in question.answer_set.all %}
            <p><input type="radio" name="answer" id="answer{{ forloop.counter }}" value="{{ answer.id }}">
            <label for="answer{{ forloop.counter }}">{{ answer.answer_text }}</label></p>
            {% endfor %}
        <input class="btn btn-lg btn-block" type="submit" value="Next">
    </form>
</div>
</body>
</html>